// src/middleware/index.js
// Middleware Export
export {
  default as authMiddleware,
  isTokenExpired,
  getTokenRemainingTime,
  authRequestInterceptor,
  authResponseInterceptor,
  handleUnauthorized,
  verifySession,
  authGuard,
  checkRoleAccess,
  withAuth,
  updateLastActivity,
  getLastActivity,
  checkSessionTimeout,
  withActivityTracking,
} from './authMiddleware';
export {
  default as networkMiddleware,
  initNetworkMonitoring,
  addNetworkListener,
  getNetworkState,
  isOnline,
  getConnectionType,
  isWifi,
  isCellular,
  networkRequestInterceptor,
  networkResponseInterceptor,
  retryConfig,
  retryRequest,
  queueOfflineRequest,
  getOfflineQueue,
  clearOfflineQueue,
  processOfflineQueue,
  shouldQueueOffline,
  getConnectionQuality,
  networkAwareRequest,
} from './networkMiddleware';
export {
  default as loggingMiddleware,
  LOG_LEVELS,
  LOG_CATEGORIES,
  setLogLevel,
  getLogLevel,
  debug,
  info,
  warn,
  error,
  addLogListener,
  getLogHistory,
  clearLogHistory,
  apiRequestLogger,
  apiResponseLogger,
  logNavigationEvent,
  logStateChange,
  measurePerformance,
  createLogger,
  logErrorBoundary,
  exportLogs,
  setupProductionLogging,
} from './loggingMiddleware';